{"uid":"1d577e45e793c7a4","name":"test_02_mouse_operations[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_02_mouse_operations","historyId":"44e89cdca6ad85aece0932e2f2047c1b","time":{"start":1761243551201,"stop":1761243551201,"duration":0},"description":"Test all mouse operations with visual feedback on DemoBlaze.","descriptionHtml":"<p>Test all mouse operations with visual feedback on DemoBlaze.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x562f9a782fba <unknown>\n#1 0x562f9a2076d0 <unknown>\n#2 0x562f9a28be12 <unknown>\n#3 0x562f9a28af9e <unknown>\n#4 0x562f9a28cb72 <unknown>\n#5 0x562f9a28c946 <unknown>\n#6 0x562f9a27ec03 <unknown>\n#7 0x562f9a24b7a8 <unknown>\n#8 0x562f9a24c421 <unknown>\n#9 0x562f9a747b28 <unknown>\n#10 0x562f9a74b87f <unknown>\n#11 0x562f9a72fc49 <unknown>\n#12 0x562f9a74c405 <unknown>\n#13 0x562f9a7154ff <unknown>\n#14 0x562f9a770258 <unknown>\n#15 0x562f9a770432 <unknown>\n#16 0x562f9a781fa3 <unknown>\n#17 0x7fb7b669caa4 <unknown>\n#18 0x7fb7b6729c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55c1e93cdfba <unknown>\nE   #1 0x55c1e8e526d0 <unknown>\nE   #2 0x55c1e8ed6e12 <unknown>\nE   #3 0x55c1e8ed5f9e <unknown>\nE   #4 0x55c1e8ed7b72 <unknown>\nE   #5 0x55c1e8ed7946 <unknown>\nE   #6 0x55c1e8ec9c03 <unknown>\nE   #7 0x55c1e8e967a8 <unknown>\nE   #8 0x55c1e8e97421 <unknown>\nE   #9 0x55c1e9392b28 <unknown>\nE   #10 0x55c1e939687f <unknown>\nE   #11 0x55c1e937ac49 <unknown>\nE   #12 0x55c1e9397405 <unknown>\nE   #13 0x55c1e93604ff <unknown>\nE   #14 0x55c1e93bb258 <unknown>\nE   #15 0x55c1e93bb432 <unknown>\nE   #16 0x55c1e93ccfa3 <unknown>\nE   #17 0x7f25fa09caa4 <unknown>\nE   #18 0x7f25fa129c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x562f9a782fba <unknown>\nE   #1 0x562f9a2076d0 <unknown>\nE   #2 0x562f9a28be12 <unknown>\nE   #3 0x562f9a28af9e <unknown>\nE   #4 0x562f9a28cb72 <unknown>\nE   #5 0x562f9a28c946 <unknown>\nE   #6 0x562f9a27ec03 <unknown>\nE   #7 0x562f9a24b7a8 <unknown>\nE   #8 0x562f9a24c421 <unknown>\nE   #9 0x562f9a747b28 <unknown>\nE   #10 0x562f9a74b87f <unknown>\nE   #11 0x562f9a72fc49 <unknown>\nE   #12 0x562f9a74c405 <unknown>\nE   #13 0x562f9a7154ff <unknown>\nE   #14 0x562f9a770258 <unknown>\nE   #15 0x562f9a770432 <unknown>\nE   #16 0x562f9a781fa3 <unknown>\nE   #17 0x7fb7b669caa4 <unknown>\nE   #18 0x7fb7b6729c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551202,"stop":1761243551417,"duration":215},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243551418,"stop":1761243552570,"duration":1152},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x562f9a782fba <unknown>\n#1 0x562f9a2076d0 <unknown>\n#2 0x562f9a28be12 <unknown>\n#3 0x562f9a28af9e <unknown>\n#4 0x562f9a28cb72 <unknown>\n#5 0x562f9a28c946 <unknown>\n#6 0x562f9a27ec03 <unknown>\n#7 0x562f9a24b7a8 <unknown>\n#8 0x562f9a24c421 <unknown>\n#9 0x562f9a747b28 <unknown>\n#10 0x562f9a74b87f <unknown>\n#11 0x562f9a72fc49 <unknown>\n#12 0x562f9a74c405 <unknown>\n#13 0x562f9a7154ff <unknown>\n#14 0x562f9a770258 <unknown>\n#15 0x562f9a770432 <unknown>\n#16 0x562f9a781fa3 <unknown>\n#17 0x7fb7b669caa4 <unknown>\n#18 0x7fb7b6729c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"Test all mouse operations with visual feedback on DemoBlaze.","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x562f9a782fba <unknown>\n#1 0x562f9a2076d0 <unknown>\n#2 0x562f9a28be12 <unknown>\n#3 0x562f9a28af9e <unknown>\n#4 0x562f9a28cb72 <unknown>\n#5 0x562f9a28c946 <unknown>\n#6 0x562f9a27ec03 <unknown>\n#7 0x562f9a24b7a8 <unknown>\n#8 0x562f9a24c421 <unknown>\n#9 0x562f9a747b28 <unknown>\n#10 0x562f9a74b87f <unknown>\n#11 0x562f9a72fc49 <unknown>\n#12 0x562f9a74c405 <unknown>\n#13 0x562f9a7154ff <unknown>\n#14 0x562f9a770258 <unknown>\n#15 0x562f9a770432 <unknown>\n#16 0x562f9a781fa3 <unknown>\n#17 0x7fb7b669caa4 <unknown>\n#18 0x7fb7b6729c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55c1e93cdfba <unknown>\nE   #1 0x55c1e8e526d0 <unknown>\nE   #2 0x55c1e8ed6e12 <unknown>\nE   #3 0x55c1e8ed5f9e <unknown>\nE   #4 0x55c1e8ed7b72 <unknown>\nE   #5 0x55c1e8ed7946 <unknown>\nE   #6 0x55c1e8ec9c03 <unknown>\nE   #7 0x55c1e8e967a8 <unknown>\nE   #8 0x55c1e8e97421 <unknown>\nE   #9 0x55c1e9392b28 <unknown>\nE   #10 0x55c1e939687f <unknown>\nE   #11 0x55c1e937ac49 <unknown>\nE   #12 0x55c1e9397405 <unknown>\nE   #13 0x55c1e93604ff <unknown>\nE   #14 0x55c1e93bb258 <unknown>\nE   #15 0x55c1e93bb432 <unknown>\nE   #16 0x55c1e93ccfa3 <unknown>\nE   #17 0x7f25fa09caa4 <unknown>\nE   #18 0x7f25fa129c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x562f9a782fba <unknown>\nE   #1 0x562f9a2076d0 <unknown>\nE   #2 0x562f9a28be12 <unknown>\nE   #3 0x562f9a28af9e <unknown>\nE   #4 0x562f9a28cb72 <unknown>\nE   #5 0x562f9a28c946 <unknown>\nE   #6 0x562f9a27ec03 <unknown>\nE   #7 0x562f9a24b7a8 <unknown>\nE   #8 0x562f9a24c421 <unknown>\nE   #9 0x562f9a747b28 <unknown>\nE   #10 0x562f9a74b87f <unknown>\nE   #11 0x562f9a72fc49 <unknown>\nE   #12 0x562f9a74c405 <unknown>\nE   #13 0x562f9a7154ff <unknown>\nE   #14 0x562f9a770258 <unknown>\nE   #15 0x562f9a770432 <unknown>\nE   #16 0x562f9a781fa3 <unknown>\nE   #17 0x7fb7b669caa4 <unknown>\nE   #18 0x7fb7b6729c6c <unknown>","steps":[],"attachments":[{"uid":"3fa8e3396f0abe20","name":"log","source":"3fa8e3396f0abe20.txt","type":"text/plain","size":12592},{"uid":"62ba9e8e09572941","name":"stdout","source":"62ba9e8e09572941.txt","type":"text/plain","size":865},{"uid":"e317a3e5b11fc4c5","name":"stderr","source":"e317a3e5b11fc4c5.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555416,"stop":1761243555416,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"story","value":"Test All Mouse Actions"},{"name":"feature","value":"Mouse Operations"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3440-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"3bd5fe3ce1450ff3","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/3bd5fe3ce1450ff3","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243136599,"stop":1761243136599,"duration":0}}]},"tags":[]},"source":"1d577e45e793c7a4.json","parameterValues":["'edge'"]}