{"uid":"34f917e9b65fb797","name":"test_05_alerts_handling[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_05_alerts_handling","historyId":"c0e9249d4f102437f6119fa11051c0e1","time":{"start":1761243552854,"stop":1761243552854,"duration":0},"description":"Test handling of alerts.","descriptionHtml":"<p>Test handling of alerts.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x55fce4e73fba <unknown>\n#1 0x55fce48f86d0 <unknown>\n#2 0x55fce497ce12 <unknown>\n#3 0x55fce497bf9e <unknown>\n#4 0x55fce497db72 <unknown>\n#5 0x55fce497d946 <unknown>\n#6 0x55fce496fc03 <unknown>\n#7 0x55fce493c7a8 <unknown>\n#8 0x55fce493d421 <unknown>\n#9 0x55fce4e38b28 <unknown>\n#10 0x55fce4e3c87f <unknown>\n#11 0x55fce4e20c49 <unknown>\n#12 0x55fce4e3d405 <unknown>\n#13 0x55fce4e064ff <unknown>\n#14 0x55fce4e61258 <unknown>\n#15 0x55fce4e61432 <unknown>\n#16 0x55fce4e72fa3 <unknown>\n#17 0x7f955d49caa4 <unknown>\n#18 0x7f955d529c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55d300fdcfba <unknown>\nE   #1 0x55d300a616d0 <unknown>\nE   #2 0x55d300ae5e12 <unknown>\nE   #3 0x55d300ae4f9e <unknown>\nE   #4 0x55d300ae6b72 <unknown>\nE   #5 0x55d300ae6946 <unknown>\nE   #6 0x55d300ad8c03 <unknown>\nE   #7 0x55d300aa57a8 <unknown>\nE   #8 0x55d300aa6421 <unknown>\nE   #9 0x55d300fa1b28 <unknown>\nE   #10 0x55d300fa587f <unknown>\nE   #11 0x55d300f89c49 <unknown>\nE   #12 0x55d300fa6405 <unknown>\nE   #13 0x55d300f6f4ff <unknown>\nE   #14 0x55d300fca258 <unknown>\nE   #15 0x55d300fca432 <unknown>\nE   #16 0x55d300fdbfa3 <unknown>\nE   #17 0x7f5fcac9caa4 <unknown>\nE   #18 0x7f5fcad29c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55fce4e73fba <unknown>\nE   #1 0x55fce48f86d0 <unknown>\nE   #2 0x55fce497ce12 <unknown>\nE   #3 0x55fce497bf9e <unknown>\nE   #4 0x55fce497db72 <unknown>\nE   #5 0x55fce497d946 <unknown>\nE   #6 0x55fce496fc03 <unknown>\nE   #7 0x55fce493c7a8 <unknown>\nE   #8 0x55fce493d421 <unknown>\nE   #9 0x55fce4e38b28 <unknown>\nE   #10 0x55fce4e3c87f <unknown>\nE   #11 0x55fce4e20c49 <unknown>\nE   #12 0x55fce4e3d405 <unknown>\nE   #13 0x55fce4e064ff <unknown>\nE   #14 0x55fce4e61258 <unknown>\nE   #15 0x55fce4e61432 <unknown>\nE   #16 0x55fce4e72fa3 <unknown>\nE   #17 0x7f955d49caa4 <unknown>\nE   #18 0x7f955d529c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551203,"stop":1761243551418,"duration":215},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551418,"stop":1761243551418,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551419,"stop":1761243551419,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243552856,"stop":1761243553976,"duration":1120},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x55fce4e73fba <unknown>\n#1 0x55fce48f86d0 <unknown>\n#2 0x55fce497ce12 <unknown>\n#3 0x55fce497bf9e <unknown>\n#4 0x55fce497db72 <unknown>\n#5 0x55fce497d946 <unknown>\n#6 0x55fce496fc03 <unknown>\n#7 0x55fce493c7a8 <unknown>\n#8 0x55fce493d421 <unknown>\n#9 0x55fce4e38b28 <unknown>\n#10 0x55fce4e3c87f <unknown>\n#11 0x55fce4e20c49 <unknown>\n#12 0x55fce4e3d405 <unknown>\n#13 0x55fce4e064ff <unknown>\n#14 0x55fce4e61258 <unknown>\n#15 0x55fce4e61432 <unknown>\n#16 0x55fce4e72fa3 <unknown>\n#17 0x7f955d49caa4 <unknown>\n#18 0x7f955d529c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"Test handling of alerts.","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x55fce4e73fba <unknown>\n#1 0x55fce48f86d0 <unknown>\n#2 0x55fce497ce12 <unknown>\n#3 0x55fce497bf9e <unknown>\n#4 0x55fce497db72 <unknown>\n#5 0x55fce497d946 <unknown>\n#6 0x55fce496fc03 <unknown>\n#7 0x55fce493c7a8 <unknown>\n#8 0x55fce493d421 <unknown>\n#9 0x55fce4e38b28 <unknown>\n#10 0x55fce4e3c87f <unknown>\n#11 0x55fce4e20c49 <unknown>\n#12 0x55fce4e3d405 <unknown>\n#13 0x55fce4e064ff <unknown>\n#14 0x55fce4e61258 <unknown>\n#15 0x55fce4e61432 <unknown>\n#16 0x55fce4e72fa3 <unknown>\n#17 0x7f955d49caa4 <unknown>\n#18 0x7f955d529c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55d300fdcfba <unknown>\nE   #1 0x55d300a616d0 <unknown>\nE   #2 0x55d300ae5e12 <unknown>\nE   #3 0x55d300ae4f9e <unknown>\nE   #4 0x55d300ae6b72 <unknown>\nE   #5 0x55d300ae6946 <unknown>\nE   #6 0x55d300ad8c03 <unknown>\nE   #7 0x55d300aa57a8 <unknown>\nE   #8 0x55d300aa6421 <unknown>\nE   #9 0x55d300fa1b28 <unknown>\nE   #10 0x55d300fa587f <unknown>\nE   #11 0x55d300f89c49 <unknown>\nE   #12 0x55d300fa6405 <unknown>\nE   #13 0x55d300f6f4ff <unknown>\nE   #14 0x55d300fca258 <unknown>\nE   #15 0x55d300fca432 <unknown>\nE   #16 0x55d300fdbfa3 <unknown>\nE   #17 0x7f5fcac9caa4 <unknown>\nE   #18 0x7f5fcad29c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55fce4e73fba <unknown>\nE   #1 0x55fce48f86d0 <unknown>\nE   #2 0x55fce497ce12 <unknown>\nE   #3 0x55fce497bf9e <unknown>\nE   #4 0x55fce497db72 <unknown>\nE   #5 0x55fce497d946 <unknown>\nE   #6 0x55fce496fc03 <unknown>\nE   #7 0x55fce493c7a8 <unknown>\nE   #8 0x55fce493d421 <unknown>\nE   #9 0x55fce4e38b28 <unknown>\nE   #10 0x55fce4e3c87f <unknown>\nE   #11 0x55fce4e20c49 <unknown>\nE   #12 0x55fce4e3d405 <unknown>\nE   #13 0x55fce4e064ff <unknown>\nE   #14 0x55fce4e61258 <unknown>\nE   #15 0x55fce4e61432 <unknown>\nE   #16 0x55fce4e72fa3 <unknown>\nE   #17 0x7f955d49caa4 <unknown>\nE   #18 0x7f955d529c6c <unknown>","steps":[],"attachments":[{"uid":"a2a9a0043bb8e5fc","name":"log","source":"a2a9a0043bb8e5fc.txt","type":"text/plain","size":7699},{"uid":"7f35f94983cb0e93","name":"stdout","source":"7f35f94983cb0e93.txt","type":"text/plain","size":702},{"uid":"6e56034c711a51b6","name":"stderr","source":"6e56034c711a51b6.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555421,"stop":1761243555421,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"feature","value":"Alerts and Popups"},{"name":"story","value":"Test Alert Handling"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3437-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"c42d1bea02282e47","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/c42d1bea02282e47","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243137069,"stop":1761243137069,"duration":0}}]},"tags":[]},"source":"34f917e9b65fb797.json","parameterValues":["'edge'"]}