{"uid":"378f0a81dc6805a1","name":"test_11_data_driven_xml[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_11_data_driven_xml","historyId":"7781d29f75130cab09c33f24d0178dae","time":{"start":1761243554109,"stop":1761243554109,"duration":0},"description":"\n        MODIFIED: Test now reads data from data/test_data.xml and performs UI actions.\n        ","descriptionHtml":"<pre><code>    MODIFIED: Test now reads data from data/test_data.xml and performs UI actions.\n</code></pre>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x55bad4ce0fba <unknown>\n#1 0x55bad47656d0 <unknown>\n#2 0x55bad47e9e12 <unknown>\n#3 0x55bad47e8f9e <unknown>\n#4 0x55bad47eab72 <unknown>\n#5 0x55bad47ea946 <unknown>\n#6 0x55bad47dcc03 <unknown>\n#7 0x55bad47a97a8 <unknown>\n#8 0x55bad47aa421 <unknown>\n#9 0x55bad4ca5b28 <unknown>\n#10 0x55bad4ca987f <unknown>\n#11 0x55bad4c8dc49 <unknown>\n#12 0x55bad4caa405 <unknown>\n#13 0x55bad4c734ff <unknown>\n#14 0x55bad4cce258 <unknown>\n#15 0x55bad4cce432 <unknown>\n#16 0x55bad4cdffa3 <unknown>\n#17 0x7f7d1269caa4 <unknown>\n#18 0x7f7d12729c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55d4bc352fba <unknown>\nE   #1 0x55d4bbdd76d0 <unknown>\nE   #2 0x55d4bbe5be12 <unknown>\nE   #3 0x55d4bbe5af9e <unknown>\nE   #4 0x55d4bbe5cb72 <unknown>\nE   #5 0x55d4bbe5c946 <unknown>\nE   #6 0x55d4bbe4ec03 <unknown>\nE   #7 0x55d4bbe1b7a8 <unknown>\nE   #8 0x55d4bbe1c421 <unknown>\nE   #9 0x55d4bc317b28 <unknown>\nE   #10 0x55d4bc31b87f <unknown>\nE   #11 0x55d4bc2ffc49 <unknown>\nE   #12 0x55d4bc31c405 <unknown>\nE   #13 0x55d4bc2e54ff <unknown>\nE   #14 0x55d4bc340258 <unknown>\nE   #15 0x55d4bc340432 <unknown>\nE   #16 0x55d4bc351fa3 <unknown>\nE   #17 0x7fbffb29caa4 <unknown>\nE   #18 0x7fbffb329c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55bad4ce0fba <unknown>\nE   #1 0x55bad47656d0 <unknown>\nE   #2 0x55bad47e9e12 <unknown>\nE   #3 0x55bad47e8f9e <unknown>\nE   #4 0x55bad47eab72 <unknown>\nE   #5 0x55bad47ea946 <unknown>\nE   #6 0x55bad47dcc03 <unknown>\nE   #7 0x55bad47a97a8 <unknown>\nE   #8 0x55bad47aa421 <unknown>\nE   #9 0x55bad4ca5b28 <unknown>\nE   #10 0x55bad4ca987f <unknown>\nE   #11 0x55bad4c8dc49 <unknown>\nE   #12 0x55bad4caa405 <unknown>\nE   #13 0x55bad4c734ff <unknown>\nE   #14 0x55bad4cce258 <unknown>\nE   #15 0x55bad4cce432 <unknown>\nE   #16 0x55bad4cdffa3 <unknown>\nE   #17 0x7f7d1269caa4 <unknown>\nE   #18 0x7f7d12729c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551203,"stop":1761243551418,"duration":215},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551418,"stop":1761243551418,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551419,"stop":1761243551419,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243554111,"stop":1761243555226,"duration":1115},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x55bad4ce0fba <unknown>\n#1 0x55bad47656d0 <unknown>\n#2 0x55bad47e9e12 <unknown>\n#3 0x55bad47e8f9e <unknown>\n#4 0x55bad47eab72 <unknown>\n#5 0x55bad47ea946 <unknown>\n#6 0x55bad47dcc03 <unknown>\n#7 0x55bad47a97a8 <unknown>\n#8 0x55bad47aa421 <unknown>\n#9 0x55bad4ca5b28 <unknown>\n#10 0x55bad4ca987f <unknown>\n#11 0x55bad4c8dc49 <unknown>\n#12 0x55bad4caa405 <unknown>\n#13 0x55bad4c734ff <unknown>\n#14 0x55bad4cce258 <unknown>\n#15 0x55bad4cce432 <unknown>\n#16 0x55bad4cdffa3 <unknown>\n#17 0x7f7d1269caa4 <unknown>\n#18 0x7f7d12729c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"\n        MODIFIED: Test now reads data from data/test_data.xml and performs UI actions.\n        ","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x55bad4ce0fba <unknown>\n#1 0x55bad47656d0 <unknown>\n#2 0x55bad47e9e12 <unknown>\n#3 0x55bad47e8f9e <unknown>\n#4 0x55bad47eab72 <unknown>\n#5 0x55bad47ea946 <unknown>\n#6 0x55bad47dcc03 <unknown>\n#7 0x55bad47a97a8 <unknown>\n#8 0x55bad47aa421 <unknown>\n#9 0x55bad4ca5b28 <unknown>\n#10 0x55bad4ca987f <unknown>\n#11 0x55bad4c8dc49 <unknown>\n#12 0x55bad4caa405 <unknown>\n#13 0x55bad4c734ff <unknown>\n#14 0x55bad4cce258 <unknown>\n#15 0x55bad4cce432 <unknown>\n#16 0x55bad4cdffa3 <unknown>\n#17 0x7f7d1269caa4 <unknown>\n#18 0x7f7d12729c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55d4bc352fba <unknown>\nE   #1 0x55d4bbdd76d0 <unknown>\nE   #2 0x55d4bbe5be12 <unknown>\nE   #3 0x55d4bbe5af9e <unknown>\nE   #4 0x55d4bbe5cb72 <unknown>\nE   #5 0x55d4bbe5c946 <unknown>\nE   #6 0x55d4bbe4ec03 <unknown>\nE   #7 0x55d4bbe1b7a8 <unknown>\nE   #8 0x55d4bbe1c421 <unknown>\nE   #9 0x55d4bc317b28 <unknown>\nE   #10 0x55d4bc31b87f <unknown>\nE   #11 0x55d4bc2ffc49 <unknown>\nE   #12 0x55d4bc31c405 <unknown>\nE   #13 0x55d4bc2e54ff <unknown>\nE   #14 0x55d4bc340258 <unknown>\nE   #15 0x55d4bc340432 <unknown>\nE   #16 0x55d4bc351fa3 <unknown>\nE   #17 0x7fbffb29caa4 <unknown>\nE   #18 0x7fbffb329c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55bad4ce0fba <unknown>\nE   #1 0x55bad47656d0 <unknown>\nE   #2 0x55bad47e9e12 <unknown>\nE   #3 0x55bad47e8f9e <unknown>\nE   #4 0x55bad47eab72 <unknown>\nE   #5 0x55bad47ea946 <unknown>\nE   #6 0x55bad47dcc03 <unknown>\nE   #7 0x55bad47a97a8 <unknown>\nE   #8 0x55bad47aa421 <unknown>\nE   #9 0x55bad4ca5b28 <unknown>\nE   #10 0x55bad4ca987f <unknown>\nE   #11 0x55bad4c8dc49 <unknown>\nE   #12 0x55bad4caa405 <unknown>\nE   #13 0x55bad4c734ff <unknown>\nE   #14 0x55bad4cce258 <unknown>\nE   #15 0x55bad4cce432 <unknown>\nE   #16 0x55bad4cdffa3 <unknown>\nE   #17 0x7f7d1269caa4 <unknown>\nE   #18 0x7f7d12729c6c <unknown>","steps":[],"attachments":[{"uid":"f63fec9aa59e9db0","name":"log","source":"f63fec9aa59e9db0.txt","type":"text/plain","size":7699},{"uid":"207acc553c64d10c","name":"stdout","source":"207acc553c64d10c.txt","type":"text/plain","size":863},{"uid":"abe38742179b7c3d","name":"stderr","source":"abe38742179b7c3d.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555421,"stop":1761243555421,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"feature","value":"Data Driven Testing"},{"name":"story","value":"Test with XML Data"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3437-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"c34999620f8fab2f","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/c34999620f8fab2f","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243137230,"stop":1761243137230,"duration":0}}]},"tags":[]},"source":"378f0a81dc6805a1.json","parameterValues":["'edge'"]}