{"uid":"48bc67051798a152","name":"test_06_cookie_operations[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_06_cookie_operations","historyId":"db8d719c54a355d5538062e91a02ffaf","time":{"start":1761243552849,"stop":1761243552849,"duration":0},"description":"Test cookie operations.","descriptionHtml":"<p>Test cookie operations.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x5566e6221fba <unknown>\n#1 0x5566e5ca66d0 <unknown>\n#2 0x5566e5d2ae12 <unknown>\n#3 0x5566e5d29f9e <unknown>\n#4 0x5566e5d2bb72 <unknown>\n#5 0x5566e5d2b946 <unknown>\n#6 0x5566e5d1dc03 <unknown>\n#7 0x5566e5cea7a8 <unknown>\n#8 0x5566e5ceb421 <unknown>\n#9 0x5566e61e6b28 <unknown>\n#10 0x5566e61ea87f <unknown>\n#11 0x5566e61cec49 <unknown>\n#12 0x5566e61eb405 <unknown>\n#13 0x5566e61b44ff <unknown>\n#14 0x5566e620f258 <unknown>\n#15 0x5566e620f432 <unknown>\n#16 0x5566e6220fa3 <unknown>\n#17 0x7f70fb69caa4 <unknown>\n#18 0x7f70fb729c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55b21ce47fba <unknown>\nE   #1 0x55b21c8cc6d0 <unknown>\nE   #2 0x55b21c950e12 <unknown>\nE   #3 0x55b21c94ff9e <unknown>\nE   #4 0x55b21c951b72 <unknown>\nE   #5 0x55b21c951946 <unknown>\nE   #6 0x55b21c943c03 <unknown>\nE   #7 0x55b21c9107a8 <unknown>\nE   #8 0x55b21c911421 <unknown>\nE   #9 0x55b21ce0cb28 <unknown>\nE   #10 0x55b21ce1087f <unknown>\nE   #11 0x55b21cdf4c49 <unknown>\nE   #12 0x55b21ce11405 <unknown>\nE   #13 0x55b21cdda4ff <unknown>\nE   #14 0x55b21ce35258 <unknown>\nE   #15 0x55b21ce35432 <unknown>\nE   #16 0x55b21ce46fa3 <unknown>\nE   #17 0x7f5c23e9caa4 <unknown>\nE   #18 0x7f5c23f29c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x5566e6221fba <unknown>\nE   #1 0x5566e5ca66d0 <unknown>\nE   #2 0x5566e5d2ae12 <unknown>\nE   #3 0x5566e5d29f9e <unknown>\nE   #4 0x5566e5d2bb72 <unknown>\nE   #5 0x5566e5d2b946 <unknown>\nE   #6 0x5566e5d1dc03 <unknown>\nE   #7 0x5566e5cea7a8 <unknown>\nE   #8 0x5566e5ceb421 <unknown>\nE   #9 0x5566e61e6b28 <unknown>\nE   #10 0x5566e61ea87f <unknown>\nE   #11 0x5566e61cec49 <unknown>\nE   #12 0x5566e61eb405 <unknown>\nE   #13 0x5566e61b44ff <unknown>\nE   #14 0x5566e620f258 <unknown>\nE   #15 0x5566e620f432 <unknown>\nE   #16 0x5566e6220fa3 <unknown>\nE   #17 0x7f70fb69caa4 <unknown>\nE   #18 0x7f70fb729c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551202,"stop":1761243551417,"duration":215},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243552851,"stop":1761243553978,"duration":1127},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x5566e6221fba <unknown>\n#1 0x5566e5ca66d0 <unknown>\n#2 0x5566e5d2ae12 <unknown>\n#3 0x5566e5d29f9e <unknown>\n#4 0x5566e5d2bb72 <unknown>\n#5 0x5566e5d2b946 <unknown>\n#6 0x5566e5d1dc03 <unknown>\n#7 0x5566e5cea7a8 <unknown>\n#8 0x5566e5ceb421 <unknown>\n#9 0x5566e61e6b28 <unknown>\n#10 0x5566e61ea87f <unknown>\n#11 0x5566e61cec49 <unknown>\n#12 0x5566e61eb405 <unknown>\n#13 0x5566e61b44ff <unknown>\n#14 0x5566e620f258 <unknown>\n#15 0x5566e620f432 <unknown>\n#16 0x5566e6220fa3 <unknown>\n#17 0x7f70fb69caa4 <unknown>\n#18 0x7f70fb729c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"Test cookie operations.","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x5566e6221fba <unknown>\n#1 0x5566e5ca66d0 <unknown>\n#2 0x5566e5d2ae12 <unknown>\n#3 0x5566e5d29f9e <unknown>\n#4 0x5566e5d2bb72 <unknown>\n#5 0x5566e5d2b946 <unknown>\n#6 0x5566e5d1dc03 <unknown>\n#7 0x5566e5cea7a8 <unknown>\n#8 0x5566e5ceb421 <unknown>\n#9 0x5566e61e6b28 <unknown>\n#10 0x5566e61ea87f <unknown>\n#11 0x5566e61cec49 <unknown>\n#12 0x5566e61eb405 <unknown>\n#13 0x5566e61b44ff <unknown>\n#14 0x5566e620f258 <unknown>\n#15 0x5566e620f432 <unknown>\n#16 0x5566e6220fa3 <unknown>\n#17 0x7f70fb69caa4 <unknown>\n#18 0x7f70fb729c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55b21ce47fba <unknown>\nE   #1 0x55b21c8cc6d0 <unknown>\nE   #2 0x55b21c950e12 <unknown>\nE   #3 0x55b21c94ff9e <unknown>\nE   #4 0x55b21c951b72 <unknown>\nE   #5 0x55b21c951946 <unknown>\nE   #6 0x55b21c943c03 <unknown>\nE   #7 0x55b21c9107a8 <unknown>\nE   #8 0x55b21c911421 <unknown>\nE   #9 0x55b21ce0cb28 <unknown>\nE   #10 0x55b21ce1087f <unknown>\nE   #11 0x55b21cdf4c49 <unknown>\nE   #12 0x55b21ce11405 <unknown>\nE   #13 0x55b21cdda4ff <unknown>\nE   #14 0x55b21ce35258 <unknown>\nE   #15 0x55b21ce35432 <unknown>\nE   #16 0x55b21ce46fa3 <unknown>\nE   #17 0x7f5c23e9caa4 <unknown>\nE   #18 0x7f5c23f29c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x5566e6221fba <unknown>\nE   #1 0x5566e5ca66d0 <unknown>\nE   #2 0x5566e5d2ae12 <unknown>\nE   #3 0x5566e5d29f9e <unknown>\nE   #4 0x5566e5d2bb72 <unknown>\nE   #5 0x5566e5d2b946 <unknown>\nE   #6 0x5566e5d1dc03 <unknown>\nE   #7 0x5566e5cea7a8 <unknown>\nE   #8 0x5566e5ceb421 <unknown>\nE   #9 0x5566e61e6b28 <unknown>\nE   #10 0x5566e61ea87f <unknown>\nE   #11 0x5566e61cec49 <unknown>\nE   #12 0x5566e61eb405 <unknown>\nE   #13 0x5566e61b44ff <unknown>\nE   #14 0x5566e620f258 <unknown>\nE   #15 0x5566e620f432 <unknown>\nE   #16 0x5566e6220fa3 <unknown>\nE   #17 0x7f70fb69caa4 <unknown>\nE   #18 0x7f70fb729c6c <unknown>","steps":[],"attachments":[{"uid":"1e0a2a53236f87dd","name":"log","source":"1e0a2a53236f87dd.txt","type":"text/plain","size":7699},{"uid":"23d2712ac4714fab","name":"stdout","source":"23d2712ac4714fab.txt","type":"text/plain","size":702},{"uid":"86c7845effd66317","name":"stderr","source":"86c7845effd66317.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555416,"stop":1761243555416,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"feature","value":"Cookies"},{"name":"story","value":"Test Cookie Operations"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3440-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"5ce955e40f6aa5f7","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/5ce955e40f6aa5f7","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243137067,"stop":1761243137067,"duration":0}}]},"tags":[]},"source":"48bc67051798a152.json","parameterValues":["'edge'"]}