{"uid":"8b3ced45f0a26dfe","name":"test_01_browser_windows_and_tabs[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_01_browser_windows_and_tabs","historyId":"6ecd3f051b815e3103ceb6eb51d60e2f","time":{"start":1761243551201,"stop":1761243551201,"duration":0},"description":"Test handling multiple windows and tabs.","descriptionHtml":"<p>Test handling multiple windows and tabs.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x55da4371ffba <unknown>\n#1 0x55da431a46d0 <unknown>\n#2 0x55da43228e12 <unknown>\n#3 0x55da43227f9e <unknown>\n#4 0x55da43229b72 <unknown>\n#5 0x55da43229946 <unknown>\n#6 0x55da4321bc03 <unknown>\n#7 0x55da431e87a8 <unknown>\n#8 0x55da431e9421 <unknown>\n#9 0x55da436e4b28 <unknown>\n#10 0x55da436e887f <unknown>\n#11 0x55da436ccc49 <unknown>\n#12 0x55da436e9405 <unknown>\n#13 0x55da436b24ff <unknown>\n#14 0x55da4370d258 <unknown>\n#15 0x55da4370d432 <unknown>\n#16 0x55da4371efa3 <unknown>\n#17 0x7f858ac9caa4 <unknown>\n#18 0x7f858ad29c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x561678c31fba <unknown>\nE   #1 0x5616786b66d0 <unknown>\nE   #2 0x56167873ae12 <unknown>\nE   #3 0x561678739f9e <unknown>\nE   #4 0x56167873bb72 <unknown>\nE   #5 0x56167873b946 <unknown>\nE   #6 0x56167872dc03 <unknown>\nE   #7 0x5616786fa7a8 <unknown>\nE   #8 0x5616786fb421 <unknown>\nE   #9 0x561678bf6b28 <unknown>\nE   #10 0x561678bfa87f <unknown>\nE   #11 0x561678bdec49 <unknown>\nE   #12 0x561678bfb405 <unknown>\nE   #13 0x561678bc44ff <unknown>\nE   #14 0x561678c1f258 <unknown>\nE   #15 0x561678c1f432 <unknown>\nE   #16 0x561678c30fa3 <unknown>\nE   #17 0x7f88b049caa4 <unknown>\nE   #18 0x7f88b0529c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55da4371ffba <unknown>\nE   #1 0x55da431a46d0 <unknown>\nE   #2 0x55da43228e12 <unknown>\nE   #3 0x55da43227f9e <unknown>\nE   #4 0x55da43229b72 <unknown>\nE   #5 0x55da43229946 <unknown>\nE   #6 0x55da4321bc03 <unknown>\nE   #7 0x55da431e87a8 <unknown>\nE   #8 0x55da431e9421 <unknown>\nE   #9 0x55da436e4b28 <unknown>\nE   #10 0x55da436e887f <unknown>\nE   #11 0x55da436ccc49 <unknown>\nE   #12 0x55da436e9405 <unknown>\nE   #13 0x55da436b24ff <unknown>\nE   #14 0x55da4370d258 <unknown>\nE   #15 0x55da4370d432 <unknown>\nE   #16 0x55da4371efa3 <unknown>\nE   #17 0x7f858ac9caa4 <unknown>\nE   #18 0x7f858ad29c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551203,"stop":1761243551418,"duration":215},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551418,"stop":1761243551418,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551419,"stop":1761243551419,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243551419,"stop":1761243552570,"duration":1151},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x55da4371ffba <unknown>\n#1 0x55da431a46d0 <unknown>\n#2 0x55da43228e12 <unknown>\n#3 0x55da43227f9e <unknown>\n#4 0x55da43229b72 <unknown>\n#5 0x55da43229946 <unknown>\n#6 0x55da4321bc03 <unknown>\n#7 0x55da431e87a8 <unknown>\n#8 0x55da431e9421 <unknown>\n#9 0x55da436e4b28 <unknown>\n#10 0x55da436e887f <unknown>\n#11 0x55da436ccc49 <unknown>\n#12 0x55da436e9405 <unknown>\n#13 0x55da436b24ff <unknown>\n#14 0x55da4370d258 <unknown>\n#15 0x55da4370d432 <unknown>\n#16 0x55da4371efa3 <unknown>\n#17 0x7f858ac9caa4 <unknown>\n#18 0x7f858ad29c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"Test handling multiple windows and tabs.","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x55da4371ffba <unknown>\n#1 0x55da431a46d0 <unknown>\n#2 0x55da43228e12 <unknown>\n#3 0x55da43227f9e <unknown>\n#4 0x55da43229b72 <unknown>\n#5 0x55da43229946 <unknown>\n#6 0x55da4321bc03 <unknown>\n#7 0x55da431e87a8 <unknown>\n#8 0x55da431e9421 <unknown>\n#9 0x55da436e4b28 <unknown>\n#10 0x55da436e887f <unknown>\n#11 0x55da436ccc49 <unknown>\n#12 0x55da436e9405 <unknown>\n#13 0x55da436b24ff <unknown>\n#14 0x55da4370d258 <unknown>\n#15 0x55da4370d432 <unknown>\n#16 0x55da4371efa3 <unknown>\n#17 0x7f858ac9caa4 <unknown>\n#18 0x7f858ad29c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x561678c31fba <unknown>\nE   #1 0x5616786b66d0 <unknown>\nE   #2 0x56167873ae12 <unknown>\nE   #3 0x561678739f9e <unknown>\nE   #4 0x56167873bb72 <unknown>\nE   #5 0x56167873b946 <unknown>\nE   #6 0x56167872dc03 <unknown>\nE   #7 0x5616786fa7a8 <unknown>\nE   #8 0x5616786fb421 <unknown>\nE   #9 0x561678bf6b28 <unknown>\nE   #10 0x561678bfa87f <unknown>\nE   #11 0x561678bdec49 <unknown>\nE   #12 0x561678bfb405 <unknown>\nE   #13 0x561678bc44ff <unknown>\nE   #14 0x561678c1f258 <unknown>\nE   #15 0x561678c1f432 <unknown>\nE   #16 0x561678c30fa3 <unknown>\nE   #17 0x7f88b049caa4 <unknown>\nE   #18 0x7f88b0529c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55da4371ffba <unknown>\nE   #1 0x55da431a46d0 <unknown>\nE   #2 0x55da43228e12 <unknown>\nE   #3 0x55da43227f9e <unknown>\nE   #4 0x55da43229b72 <unknown>\nE   #5 0x55da43229946 <unknown>\nE   #6 0x55da4321bc03 <unknown>\nE   #7 0x55da431e87a8 <unknown>\nE   #8 0x55da431e9421 <unknown>\nE   #9 0x55da436e4b28 <unknown>\nE   #10 0x55da436e887f <unknown>\nE   #11 0x55da436ccc49 <unknown>\nE   #12 0x55da436e9405 <unknown>\nE   #13 0x55da436b24ff <unknown>\nE   #14 0x55da4370d258 <unknown>\nE   #15 0x55da4370d432 <unknown>\nE   #16 0x55da4371efa3 <unknown>\nE   #17 0x7f858ac9caa4 <unknown>\nE   #18 0x7f858ad29c6c <unknown>","steps":[],"attachments":[{"uid":"3eb2183d7e9ae380","name":"log","source":"3eb2183d7e9ae380.txt","type":"text/plain","size":12592},{"uid":"d9769aec00e5103d","name":"stdout","source":"d9769aec00e5103d.txt","type":"text/plain","size":865},{"uid":"b7444cf0f7307666","name":"stderr","source":"b7444cf0f7307666.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555421,"stop":1761243555421,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"feature","value":"Browser Operations"},{"name":"story","value":"Test Multiple Browser Windows and Tabs"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3437-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"f5e4d40498328372","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/f5e4d40498328372","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243136599,"stop":1761243136599,"duration":0}}]},"tags":[]},"source":"8b3ced45f0a26dfe.json","parameterValues":["'edge'"]}