{"uid":"98cdb603f6fe7d58","name":"test_04_javascript_execution[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_04_javascript_execution","historyId":"e6094228a74d11bcf713601f83713407","time":{"start":1761243552828,"stop":1761243552828,"duration":0},"description":"Test JavaScript execution.","descriptionHtml":"<p>Test JavaScript execution.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x555ec682bfba <unknown>\n#1 0x555ec62b06d0 <unknown>\n#2 0x555ec6334e12 <unknown>\n#3 0x555ec6333f9e <unknown>\n#4 0x555ec6335b72 <unknown>\n#5 0x555ec6335946 <unknown>\n#6 0x555ec6327c03 <unknown>\n#7 0x555ec62f47a8 <unknown>\n#8 0x555ec62f5421 <unknown>\n#9 0x555ec67f0b28 <unknown>\n#10 0x555ec67f487f <unknown>\n#11 0x555ec67d8c49 <unknown>\n#12 0x555ec67f5405 <unknown>\n#13 0x555ec67be4ff <unknown>\n#14 0x555ec6819258 <unknown>\n#15 0x555ec6819432 <unknown>\n#16 0x555ec682afa3 <unknown>\n#17 0x7f3c4ea9caa4 <unknown>\n#18 0x7f3c4eb29c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56173828efba <unknown>\nE   #1 0x561737d136d0 <unknown>\nE   #2 0x561737d97e12 <unknown>\nE   #3 0x561737d96f9e <unknown>\nE   #4 0x561737d98b72 <unknown>\nE   #5 0x561737d98946 <unknown>\nE   #6 0x561737d8ac03 <unknown>\nE   #7 0x561737d577a8 <unknown>\nE   #8 0x561737d58421 <unknown>\nE   #9 0x561738253b28 <unknown>\nE   #10 0x56173825787f <unknown>\nE   #11 0x56173823bc49 <unknown>\nE   #12 0x561738258405 <unknown>\nE   #13 0x5617382214ff <unknown>\nE   #14 0x56173827c258 <unknown>\nE   #15 0x56173827c432 <unknown>\nE   #16 0x56173828dfa3 <unknown>\nE   #17 0x7fe2b849caa4 <unknown>\nE   #18 0x7fe2b8529c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x555ec682bfba <unknown>\nE   #1 0x555ec62b06d0 <unknown>\nE   #2 0x555ec6334e12 <unknown>\nE   #3 0x555ec6333f9e <unknown>\nE   #4 0x555ec6335b72 <unknown>\nE   #5 0x555ec6335946 <unknown>\nE   #6 0x555ec6327c03 <unknown>\nE   #7 0x555ec62f47a8 <unknown>\nE   #8 0x555ec62f5421 <unknown>\nE   #9 0x555ec67f0b28 <unknown>\nE   #10 0x555ec67f487f <unknown>\nE   #11 0x555ec67d8c49 <unknown>\nE   #12 0x555ec67f5405 <unknown>\nE   #13 0x555ec67be4ff <unknown>\nE   #14 0x555ec6819258 <unknown>\nE   #15 0x555ec6819432 <unknown>\nE   #16 0x555ec682afa3 <unknown>\nE   #17 0x7f3c4ea9caa4 <unknown>\nE   #18 0x7f3c4eb29c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551202,"stop":1761243551418,"duration":216},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551418,"stop":1761243551418,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551418,"stop":1761243551419,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243552829,"stop":1761243553954,"duration":1125},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x555ec682bfba <unknown>\n#1 0x555ec62b06d0 <unknown>\n#2 0x555ec6334e12 <unknown>\n#3 0x555ec6333f9e <unknown>\n#4 0x555ec6335b72 <unknown>\n#5 0x555ec6335946 <unknown>\n#6 0x555ec6327c03 <unknown>\n#7 0x555ec62f47a8 <unknown>\n#8 0x555ec62f5421 <unknown>\n#9 0x555ec67f0b28 <unknown>\n#10 0x555ec67f487f <unknown>\n#11 0x555ec67d8c49 <unknown>\n#12 0x555ec67f5405 <unknown>\n#13 0x555ec67be4ff <unknown>\n#14 0x555ec6819258 <unknown>\n#15 0x555ec6819432 <unknown>\n#16 0x555ec682afa3 <unknown>\n#17 0x7f3c4ea9caa4 <unknown>\n#18 0x7f3c4eb29c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"Test JavaScript execution.","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x555ec682bfba <unknown>\n#1 0x555ec62b06d0 <unknown>\n#2 0x555ec6334e12 <unknown>\n#3 0x555ec6333f9e <unknown>\n#4 0x555ec6335b72 <unknown>\n#5 0x555ec6335946 <unknown>\n#6 0x555ec6327c03 <unknown>\n#7 0x555ec62f47a8 <unknown>\n#8 0x555ec62f5421 <unknown>\n#9 0x555ec67f0b28 <unknown>\n#10 0x555ec67f487f <unknown>\n#11 0x555ec67d8c49 <unknown>\n#12 0x555ec67f5405 <unknown>\n#13 0x555ec67be4ff <unknown>\n#14 0x555ec6819258 <unknown>\n#15 0x555ec6819432 <unknown>\n#16 0x555ec682afa3 <unknown>\n#17 0x7f3c4ea9caa4 <unknown>\n#18 0x7f3c4eb29c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56173828efba <unknown>\nE   #1 0x561737d136d0 <unknown>\nE   #2 0x561737d97e12 <unknown>\nE   #3 0x561737d96f9e <unknown>\nE   #4 0x561737d98b72 <unknown>\nE   #5 0x561737d98946 <unknown>\nE   #6 0x561737d8ac03 <unknown>\nE   #7 0x561737d577a8 <unknown>\nE   #8 0x561737d58421 <unknown>\nE   #9 0x561738253b28 <unknown>\nE   #10 0x56173825787f <unknown>\nE   #11 0x56173823bc49 <unknown>\nE   #12 0x561738258405 <unknown>\nE   #13 0x5617382214ff <unknown>\nE   #14 0x56173827c258 <unknown>\nE   #15 0x56173827c432 <unknown>\nE   #16 0x56173828dfa3 <unknown>\nE   #17 0x7fe2b849caa4 <unknown>\nE   #18 0x7fe2b8529c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x555ec682bfba <unknown>\nE   #1 0x555ec62b06d0 <unknown>\nE   #2 0x555ec6334e12 <unknown>\nE   #3 0x555ec6333f9e <unknown>\nE   #4 0x555ec6335b72 <unknown>\nE   #5 0x555ec6335946 <unknown>\nE   #6 0x555ec6327c03 <unknown>\nE   #7 0x555ec62f47a8 <unknown>\nE   #8 0x555ec62f5421 <unknown>\nE   #9 0x555ec67f0b28 <unknown>\nE   #10 0x555ec67f487f <unknown>\nE   #11 0x555ec67d8c49 <unknown>\nE   #12 0x555ec67f5405 <unknown>\nE   #13 0x555ec67be4ff <unknown>\nE   #14 0x555ec6819258 <unknown>\nE   #15 0x555ec6819432 <unknown>\nE   #16 0x555ec682afa3 <unknown>\nE   #17 0x7f3c4ea9caa4 <unknown>\nE   #18 0x7f3c4eb29c6c <unknown>","steps":[],"attachments":[{"uid":"99d3a62a1e63c4c8","name":"log","source":"99d3a62a1e63c4c8.txt","type":"text/plain","size":7699},{"uid":"a4322adde792f760","name":"stdout","source":"a4322adde792f760.txt","type":"text/plain","size":702},{"uid":"15d8d1cda25b172d","name":"stderr","source":"15d8d1cda25b172d.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555323,"stop":1761243555323,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"story","value":"Test JavaScript Execution"},{"name":"feature","value":"JavaScript Execution"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3434-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"e300a8256dd0f78","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/e300a8256dd0f78","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243137033,"stop":1761243137033,"duration":0}}]},"tags":[]},"source":"98cdb603f6fe7d58.json","parameterValues":["'edge'"]}