{"uid":"a5e6305213990b63","name":"test_08_screenshot_operations[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_08_screenshot_operations","historyId":"19ab0df6d94bf22a9cfc74d20e0ba02f","time":{"start":1761243554087,"stop":1761243554087,"duration":0},"description":"Test various screenshot operations.","descriptionHtml":"<p>Test various screenshot operations.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x5614c3c3efba <unknown>\n#1 0x5614c36c36d0 <unknown>\n#2 0x5614c3747e12 <unknown>\n#3 0x5614c3746f9e <unknown>\n#4 0x5614c3748b72 <unknown>\n#5 0x5614c3748946 <unknown>\n#6 0x5614c373ac03 <unknown>\n#7 0x5614c37077a8 <unknown>\n#8 0x5614c3708421 <unknown>\n#9 0x5614c3c03b28 <unknown>\n#10 0x5614c3c0787f <unknown>\n#11 0x5614c3bebc49 <unknown>\n#12 0x5614c3c08405 <unknown>\n#13 0x5614c3bd14ff <unknown>\n#14 0x5614c3c2c258 <unknown>\n#15 0x5614c3c2c432 <unknown>\n#16 0x5614c3c3dfa3 <unknown>\n#17 0x7f916369caa4 <unknown>\n#18 0x7f9163729c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x564128db1fba <unknown>\nE   #1 0x5641288366d0 <unknown>\nE   #2 0x5641288bae12 <unknown>\nE   #3 0x5641288b9f9e <unknown>\nE   #4 0x5641288bbb72 <unknown>\nE   #5 0x5641288bb946 <unknown>\nE   #6 0x5641288adc03 <unknown>\nE   #7 0x56412887a7a8 <unknown>\nE   #8 0x56412887b421 <unknown>\nE   #9 0x564128d76b28 <unknown>\nE   #10 0x564128d7a87f <unknown>\nE   #11 0x564128d5ec49 <unknown>\nE   #12 0x564128d7b405 <unknown>\nE   #13 0x564128d444ff <unknown>\nE   #14 0x564128d9f258 <unknown>\nE   #15 0x564128d9f432 <unknown>\nE   #16 0x564128db0fa3 <unknown>\nE   #17 0x7f2664a9caa4 <unknown>\nE   #18 0x7f2664b29c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x5614c3c3efba <unknown>\nE   #1 0x5614c36c36d0 <unknown>\nE   #2 0x5614c3747e12 <unknown>\nE   #3 0x5614c3746f9e <unknown>\nE   #4 0x5614c3748b72 <unknown>\nE   #5 0x5614c3748946 <unknown>\nE   #6 0x5614c373ac03 <unknown>\nE   #7 0x5614c37077a8 <unknown>\nE   #8 0x5614c3708421 <unknown>\nE   #9 0x5614c3c03b28 <unknown>\nE   #10 0x5614c3c0787f <unknown>\nE   #11 0x5614c3bebc49 <unknown>\nE   #12 0x5614c3c08405 <unknown>\nE   #13 0x5614c3bd14ff <unknown>\nE   #14 0x5614c3c2c258 <unknown>\nE   #15 0x5614c3c2c432 <unknown>\nE   #16 0x5614c3c3dfa3 <unknown>\nE   #17 0x7f916369caa4 <unknown>\nE   #18 0x7f9163729c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551202,"stop":1761243551418,"duration":216},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551418,"stop":1761243551418,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551418,"stop":1761243551419,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243554089,"stop":1761243555207,"duration":1118},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x5614c3c3efba <unknown>\n#1 0x5614c36c36d0 <unknown>\n#2 0x5614c3747e12 <unknown>\n#3 0x5614c3746f9e <unknown>\n#4 0x5614c3748b72 <unknown>\n#5 0x5614c3748946 <unknown>\n#6 0x5614c373ac03 <unknown>\n#7 0x5614c37077a8 <unknown>\n#8 0x5614c3708421 <unknown>\n#9 0x5614c3c03b28 <unknown>\n#10 0x5614c3c0787f <unknown>\n#11 0x5614c3bebc49 <unknown>\n#12 0x5614c3c08405 <unknown>\n#13 0x5614c3bd14ff <unknown>\n#14 0x5614c3c2c258 <unknown>\n#15 0x5614c3c2c432 <unknown>\n#16 0x5614c3c3dfa3 <unknown>\n#17 0x7f916369caa4 <unknown>\n#18 0x7f9163729c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"Test various screenshot operations.","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x5614c3c3efba <unknown>\n#1 0x5614c36c36d0 <unknown>\n#2 0x5614c3747e12 <unknown>\n#3 0x5614c3746f9e <unknown>\n#4 0x5614c3748b72 <unknown>\n#5 0x5614c3748946 <unknown>\n#6 0x5614c373ac03 <unknown>\n#7 0x5614c37077a8 <unknown>\n#8 0x5614c3708421 <unknown>\n#9 0x5614c3c03b28 <unknown>\n#10 0x5614c3c0787f <unknown>\n#11 0x5614c3bebc49 <unknown>\n#12 0x5614c3c08405 <unknown>\n#13 0x5614c3bd14ff <unknown>\n#14 0x5614c3c2c258 <unknown>\n#15 0x5614c3c2c432 <unknown>\n#16 0x5614c3c3dfa3 <unknown>\n#17 0x7f916369caa4 <unknown>\n#18 0x7f9163729c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x564128db1fba <unknown>\nE   #1 0x5641288366d0 <unknown>\nE   #2 0x5641288bae12 <unknown>\nE   #3 0x5641288b9f9e <unknown>\nE   #4 0x5641288bbb72 <unknown>\nE   #5 0x5641288bb946 <unknown>\nE   #6 0x5641288adc03 <unknown>\nE   #7 0x56412887a7a8 <unknown>\nE   #8 0x56412887b421 <unknown>\nE   #9 0x564128d76b28 <unknown>\nE   #10 0x564128d7a87f <unknown>\nE   #11 0x564128d5ec49 <unknown>\nE   #12 0x564128d7b405 <unknown>\nE   #13 0x564128d444ff <unknown>\nE   #14 0x564128d9f258 <unknown>\nE   #15 0x564128d9f432 <unknown>\nE   #16 0x564128db0fa3 <unknown>\nE   #17 0x7f2664a9caa4 <unknown>\nE   #18 0x7f2664b29c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x5614c3c3efba <unknown>\nE   #1 0x5614c36c36d0 <unknown>\nE   #2 0x5614c3747e12 <unknown>\nE   #3 0x5614c3746f9e <unknown>\nE   #4 0x5614c3748b72 <unknown>\nE   #5 0x5614c3748946 <unknown>\nE   #6 0x5614c373ac03 <unknown>\nE   #7 0x5614c37077a8 <unknown>\nE   #8 0x5614c3708421 <unknown>\nE   #9 0x5614c3c03b28 <unknown>\nE   #10 0x5614c3c0787f <unknown>\nE   #11 0x5614c3bebc49 <unknown>\nE   #12 0x5614c3c08405 <unknown>\nE   #13 0x5614c3bd14ff <unknown>\nE   #14 0x5614c3c2c258 <unknown>\nE   #15 0x5614c3c2c432 <unknown>\nE   #16 0x5614c3c3dfa3 <unknown>\nE   #17 0x7f916369caa4 <unknown>\nE   #18 0x7f9163729c6c <unknown>","steps":[],"attachments":[{"uid":"6053fc000f8f6d59","name":"log","source":"6053fc000f8f6d59.txt","type":"text/plain","size":7699},{"uid":"7a82039131382bdf","name":"stdout","source":"7a82039131382bdf.txt","type":"text/plain","size":863},{"uid":"910b442f343ca149","name":"stderr","source":"910b442f343ca149.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555323,"stop":1761243555323,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"story","value":"Test Screenshot Capabilities"},{"name":"feature","value":"Screenshots"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3434-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"c3572cc4e513fbb6","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/c3572cc4e513fbb6","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243137177,"stop":1761243137177,"duration":0}}]},"tags":[]},"source":"a5e6305213990b63.json","parameterValues":["'edge'"]}