{"uid":"cb88d9b910c1db3c","name":"test_09_wait_strategies[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_09_wait_strategies","historyId":"b962485eaede51083bd20e1c9f0ee1de","time":{"start":1761243554112,"stop":1761243554112,"duration":0},"description":"Test different wait strategies.","descriptionHtml":"<p>Test different wait strategies.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x56502d582fba <unknown>\n#1 0x56502d0076d0 <unknown>\n#2 0x56502d08be12 <unknown>\n#3 0x56502d08af9e <unknown>\n#4 0x56502d08cb72 <unknown>\n#5 0x56502d08c946 <unknown>\n#6 0x56502d07ec03 <unknown>\n#7 0x56502d04b7a8 <unknown>\n#8 0x56502d04c421 <unknown>\n#9 0x56502d547b28 <unknown>\n#10 0x56502d54b87f <unknown>\n#11 0x56502d52fc49 <unknown>\n#12 0x56502d54c405 <unknown>\n#13 0x56502d5154ff <unknown>\n#14 0x56502d570258 <unknown>\n#15 0x56502d570432 <unknown>\n#16 0x56502d581fa3 <unknown>\n#17 0x7f594fe9caa4 <unknown>\n#18 0x7f594ff29c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x5630f0189fba <unknown>\nE   #1 0x5630efc0e6d0 <unknown>\nE   #2 0x5630efc92e12 <unknown>\nE   #3 0x5630efc91f9e <unknown>\nE   #4 0x5630efc93b72 <unknown>\nE   #5 0x5630efc93946 <unknown>\nE   #6 0x5630efc85c03 <unknown>\nE   #7 0x5630efc527a8 <unknown>\nE   #8 0x5630efc53421 <unknown>\nE   #9 0x5630f014eb28 <unknown>\nE   #10 0x5630f015287f <unknown>\nE   #11 0x5630f0136c49 <unknown>\nE   #12 0x5630f0153405 <unknown>\nE   #13 0x5630f011c4ff <unknown>\nE   #14 0x5630f0177258 <unknown>\nE   #15 0x5630f0177432 <unknown>\nE   #16 0x5630f0188fa3 <unknown>\nE   #17 0x7f978de9caa4 <unknown>\nE   #18 0x7f978df29c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56502d582fba <unknown>\nE   #1 0x56502d0076d0 <unknown>\nE   #2 0x56502d08be12 <unknown>\nE   #3 0x56502d08af9e <unknown>\nE   #4 0x56502d08cb72 <unknown>\nE   #5 0x56502d08c946 <unknown>\nE   #6 0x56502d07ec03 <unknown>\nE   #7 0x56502d04b7a8 <unknown>\nE   #8 0x56502d04c421 <unknown>\nE   #9 0x56502d547b28 <unknown>\nE   #10 0x56502d54b87f <unknown>\nE   #11 0x56502d52fc49 <unknown>\nE   #12 0x56502d54c405 <unknown>\nE   #13 0x56502d5154ff <unknown>\nE   #14 0x56502d570258 <unknown>\nE   #15 0x56502d570432 <unknown>\nE   #16 0x56502d581fa3 <unknown>\nE   #17 0x7f594fe9caa4 <unknown>\nE   #18 0x7f594ff29c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551202,"stop":1761243551417,"duration":215},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243554114,"stop":1761243555233,"duration":1119},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x56502d582fba <unknown>\n#1 0x56502d0076d0 <unknown>\n#2 0x56502d08be12 <unknown>\n#3 0x56502d08af9e <unknown>\n#4 0x56502d08cb72 <unknown>\n#5 0x56502d08c946 <unknown>\n#6 0x56502d07ec03 <unknown>\n#7 0x56502d04b7a8 <unknown>\n#8 0x56502d04c421 <unknown>\n#9 0x56502d547b28 <unknown>\n#10 0x56502d54b87f <unknown>\n#11 0x56502d52fc49 <unknown>\n#12 0x56502d54c405 <unknown>\n#13 0x56502d5154ff <unknown>\n#14 0x56502d570258 <unknown>\n#15 0x56502d570432 <unknown>\n#16 0x56502d581fa3 <unknown>\n#17 0x7f594fe9caa4 <unknown>\n#18 0x7f594ff29c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"Test different wait strategies.","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x56502d582fba <unknown>\n#1 0x56502d0076d0 <unknown>\n#2 0x56502d08be12 <unknown>\n#3 0x56502d08af9e <unknown>\n#4 0x56502d08cb72 <unknown>\n#5 0x56502d08c946 <unknown>\n#6 0x56502d07ec03 <unknown>\n#7 0x56502d04b7a8 <unknown>\n#8 0x56502d04c421 <unknown>\n#9 0x56502d547b28 <unknown>\n#10 0x56502d54b87f <unknown>\n#11 0x56502d52fc49 <unknown>\n#12 0x56502d54c405 <unknown>\n#13 0x56502d5154ff <unknown>\n#14 0x56502d570258 <unknown>\n#15 0x56502d570432 <unknown>\n#16 0x56502d581fa3 <unknown>\n#17 0x7f594fe9caa4 <unknown>\n#18 0x7f594ff29c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x5630f0189fba <unknown>\nE   #1 0x5630efc0e6d0 <unknown>\nE   #2 0x5630efc92e12 <unknown>\nE   #3 0x5630efc91f9e <unknown>\nE   #4 0x5630efc93b72 <unknown>\nE   #5 0x5630efc93946 <unknown>\nE   #6 0x5630efc85c03 <unknown>\nE   #7 0x5630efc527a8 <unknown>\nE   #8 0x5630efc53421 <unknown>\nE   #9 0x5630f014eb28 <unknown>\nE   #10 0x5630f015287f <unknown>\nE   #11 0x5630f0136c49 <unknown>\nE   #12 0x5630f0153405 <unknown>\nE   #13 0x5630f011c4ff <unknown>\nE   #14 0x5630f0177258 <unknown>\nE   #15 0x5630f0177432 <unknown>\nE   #16 0x5630f0188fa3 <unknown>\nE   #17 0x7f978de9caa4 <unknown>\nE   #18 0x7f978df29c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56502d582fba <unknown>\nE   #1 0x56502d0076d0 <unknown>\nE   #2 0x56502d08be12 <unknown>\nE   #3 0x56502d08af9e <unknown>\nE   #4 0x56502d08cb72 <unknown>\nE   #5 0x56502d08c946 <unknown>\nE   #6 0x56502d07ec03 <unknown>\nE   #7 0x56502d04b7a8 <unknown>\nE   #8 0x56502d04c421 <unknown>\nE   #9 0x56502d547b28 <unknown>\nE   #10 0x56502d54b87f <unknown>\nE   #11 0x56502d52fc49 <unknown>\nE   #12 0x56502d54c405 <unknown>\nE   #13 0x56502d5154ff <unknown>\nE   #14 0x56502d570258 <unknown>\nE   #15 0x56502d570432 <unknown>\nE   #16 0x56502d581fa3 <unknown>\nE   #17 0x7f594fe9caa4 <unknown>\nE   #18 0x7f594ff29c6c <unknown>","steps":[],"attachments":[{"uid":"54a2a73cfcd05a2","name":"log","source":"54a2a73cfcd05a2.txt","type":"text/plain","size":7699},{"uid":"8a5f4e7efc36f916","name":"stdout","source":"8a5f4e7efc36f916.txt","type":"text/plain","size":863},{"uid":"4fefdc600ebb05d0","name":"stderr","source":"4fefdc600ebb05d0.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555416,"stop":1761243555416,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"feature","value":"Waits"},{"name":"story","value":"Test Different Wait Strategies"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3440-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"f7fca91670ca68db","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/f7fca91670ca68db","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243137232,"stop":1761243137232,"duration":0}}]},"tags":[]},"source":"cb88d9b910c1db3c.json","parameterValues":["'edge'"]}