INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1142 ==================================================
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1143 Starting new test on CHROME
DEBUG    selenium.webdriver.common.service:service.py:215 Started executable: `/usr/local/bin/chromedriver` in a child process with pid: 9662
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:55631/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:loggingPrefs": {"performance": "ALL"}, "goog:chromeOptions": {"prefs": {"download.default_directory": "/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/downloads", "download.prompt_for_download": false, "download.directory_upgrade": true, "safebrowsing.enabled": false, "profile.default_content_settings.popups": 0, "profile.content_settings.exceptions.automatic_downloads.*.setting": 1}, "excludeSwitches": ["enable-logging", "enable-automation"], "useAutomationExtension": false, "extensions": [], "args": ["--headless=new", "--window-size=1920,1080", "--start-maximized", "--disable-gpu", "--no-sandbox", "--disable-dev-shm-usage", "--disable-extensions", "--disable-popup-blocking", "--ignore-certificate-errors", "--disable-web-security", "--allow-running-insecure-content"]}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:244 Starting new HTTP connection (1): localhost:55631
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:55631 "POST /session HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"141.0.7390.122","chrome":{"chromedriverVersion":"141.0.7390.122 (b477534e7e10d193e916cd4e2967c589383625b2-refs/branch-heads/7390@{#2667})","userDataDir":"/tmp/.org.chromium.Chromium.zcpm30"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:46501"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"7f095d9988f0732319f3c579107b2403"}} | headers=HTTPHeaderDict({'Content-Length': '850', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:55631/session/7f095d9988f0732319f3c579107b2403/timeouts {"implicit": 10000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:55631 "POST /session/7f095d9988f0732319f3c579107b2403/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:55631/session/7f095d9988f0732319f3c579107b2403/timeouts {"pageLoad": 60000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:55631 "POST /session/7f095d9988f0732319f3c579107b2403/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.address`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.address` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.automotive`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.automotive` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.bank`.
DEBUG    faker.factory:factory.py:86 Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.barcode`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.barcode` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.color`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.color` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.company`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.company` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.credit_card`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.credit_card` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.currency`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.currency` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.date_time`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.date_time` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.geo`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.geo` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.internet`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.internet` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.job`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.job` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.lorem`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.lorem` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.misc`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.misc` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.passport`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.passport` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.person`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.person` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.phone_number`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.phone_number` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.ssn`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.ssn` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:55631/session/7f095d9988f0732319f3c579107b2403/url {"url": "https://www.demoblaze.com"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:55631 "POST /session/7f095d9988f0732319f3c579107b2403/url HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1163 Navigated to DemoBlaze website on chrome
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:2255 Testing radio button selection
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:55631/session/7f095d9988f0732319f3c579107b2403/timeouts {"pageLoad": 30000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:55631 "POST /session/7f095d9988f0732319f3c579107b2403/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:55631/session/7f095d9988f0732319f3c579107b2403/url {"url": "https://demo.seleniumeasy.com/basic-radiobutton-demo.html"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:55631 "POST /session/7f095d9988f0732319f3c579107b2403/url HTTP/1.1" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=500 | data={"value":{"error":"unknown error","message":"unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=141.0.7390.122)","stacktrace":"#0 0x56427cde0fea \u003Cunknown>\n#1 0x56427c85ed06 \u003Cunknown>\n#2 0x56427c855c30 \u003Cunknown>\n#3 0x56427c8470e6 \u003Cunknown>\n#4 0x56427c848efb \u003Cunknown>\n#5 0x56427c847686 \u003Cunknown>\n#6 0x56427c846e17 \u003Cunknown>\n#7 0x56427c846ac9 \u003Cunknown>\n#8 0x56427c844912 \u003Cunknown>\n#9 0x56427c8450ea \u003Cunknown>\n#10 0x56427c862239 \u003Cunknown>\n#11 0x56427c8fd705 \u003Cunknown>\n#12 0x56427c8d6e12 \u003Cunknown>\n#13 0x56427c8fcb3b \u003Cunknown>\n#14 0x56427c8d6be3 \u003Cunknown>\n#15 0x56427c8a32d2 \u003Cunknown>\n#16 0x56427c8a3f91 \u003Cunknown>\n#17 0x56427cda49e8 \u003Cunknown>\n#18 0x56427cda884f \u003Cunknown>\n#19 0x56427cd8bec9 \u003Cunknown>\n#20 0x56427cda93f5 \u003Cunknown>\n#21 0x56427cd7174f \u003Cunknown>\n#22 0x56427cdcdcc8 \u003Cunknown>\n#23 0x56427cdcdea3 \u003Cunknown>\n#24 0x56427cddff83 \u003Cunknown>\n#25 0x7f588269caa4 \u003Cunknown>\n#26 0x7f5882729c6c \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '1081', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
WARNING  TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:2282 Selenium Easy failed: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=141.0.7390.122)
Stacktrace:
#0 0x56427cde0fea <unknown>
#1 0x56427c85ed06 <unknown>
#2 0x56427c855c30 <unknown>
#3 0x56427c8470e6 <unknown>
#4 0x56427c848efb <unknown>
#5 0x56427c847686 <unknown>
#6 0x56427c846e17 <unknown>
#7 0x56427c846ac9 <unknown>
#8 0x56427c844912 <unknown>
#9 0x56427c8450ea <unknown>
#10 0x56427c862239 <unknown>
#11 0x56427c8fd705 <unknown>
#12 0x56427c8d6e12 <unknown>
#13 0x56427c8fcb3b <unknown>
#14 0x56427c8d6be3 <unknown>
#15 0x56427c8a32d2 <unknown>
#16 0x56427c8a3f91 <unknown>
#17 0x56427cda49e8 <unknown>
#18 0x56427cda884f <unknown>
#19 0x56427cd8bec9 <unknown>
#20 0x56427cda93f5 <unknown>
#21 0x56427cd7174f <unknown>
#22 0x56427cdcdcc8 <unknown>
#23 0x56427cdcdea3 <unknown>
#24 0x56427cddff83 <unknown>
#25 0x7f588269caa4 <unknown>
#26 0x7f5882729c6c <unknown>

DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:55631/session/7f095d9988f0732319f3c579107b2403/timeouts {"pageLoad": 59000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:55631 "POST /session/7f095d9988f0732319f3c579107b2403/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:55631/session/7f095d9988f0732319f3c579107b2403/url {"url": "https://demoqa.com/radio-button"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:55631 "POST /session/7f095d9988f0732319f3c579107b2403/url HTTP/1.1" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=500 | data={"value":{"error":"timeout","message":"timeout: Timed out receiving message from renderer: 58.533\n  (Session info: chrome=141.0.7390.122)","stacktrace":"#0 0x56427cde0fea \u003Cunknown>\n#1 0x56427c85ed06 \u003Cunknown>\n#2 0x56427c846de6 \u003Cunknown>\n#3 0x56427c846ac9 \u003Cunknown>\n#4 0x56427c844912 \u003Cunknown>\n#5 0x56427c84525f \u003Cunknown>\n#6 0x56427c853b33 \u003Cunknown>\n#7 0x56427c86d21b \u003Cunknown>\n#8 0x56427c8739bb \u003Cunknown>\n#9 0x56427c84599d \u003Cunknown>\n#10 0x56427c86cf48 \u003Cunknown>\n#11 0x56427c8fcea1 \u003Cunknown>\n#12 0x56427c8d6be3 \u003Cunknown>\n#13 0x56427c8a32d2 \u003Cunknown>\n#14 0x56427c8a3f91 \u003Cunknown>\n#15 0x56427cda49e8 \u003Cunknown>\n#16 0x56427cda884f \u003Cunknown>\n#17 0x56427cd8bec9 \u003Cunknown>\n#18 0x56427cda93f5 \u003Cunknown>\n#19 0x56427cd7174f \u003Cunknown>\n#20 0x56427cdcdcc8 \u003Cunknown>\n#21 0x56427cdcdea3 \u003Cunknown>\n#22 0x56427cddff83 \u003Cunknown>\n#23 0x7f588269caa4 \u003Cunknown>\n#24 0x7f5882729c6c \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '1022', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
WARNING  TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:2313 Demoqa failed: Message: timeout: Timed out receiving message from renderer: 58.533
  (Session info: chrome=141.0.7390.122)
Stacktrace:
#0 0x56427cde0fea <unknown>
#1 0x56427c85ed06 <unknown>
#2 0x56427c846de6 <unknown>
#3 0x56427c846ac9 <unknown>
#4 0x56427c844912 <unknown>
#5 0x56427c84525f <unknown>
#6 0x56427c853b33 <unknown>
#7 0x56427c86d21b <unknown>
#8 0x56427c8739bb <unknown>
#9 0x56427c84599d <unknown>
#10 0x56427c86cf48 <unknown>
#11 0x56427c8fcea1 <unknown>
#12 0x56427c8d6be3 <unknown>
#13 0x56427c8a32d2 <unknown>
#14 0x56427c8a3f91 <unknown>
#15 0x56427cda49e8 <unknown>
#16 0x56427cda884f <unknown>
#17 0x56427cd8bec9 <unknown>
#18 0x56427cda93f5 <unknown>
#19 0x56427cd7174f <unknown>
#20 0x56427cdcdcc8 <unknown>
#21 0x56427cdcdea3 <unknown>
#22 0x56427cddff83 <unknown>
#23 0x7f588269caa4 <unknown>
#24 0x7f5882729c6c <unknown>
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1168 Test completed on chrome
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1169 ==================================================
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 DELETE http://localhost:55631/session/7f095d9988f0732319f3c579107b2403 {}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:55631 "DELETE /session/7f095d9988f0732319f3c579107b2403 HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request