INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1142 ==================================================
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1143 Starting new test on CHROME
DEBUG    selenium.webdriver.common.service:service.py:215 Started executable: `/usr/local/bin/chromedriver` in a child process with pid: 10017
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:44135/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:loggingPrefs": {"performance": "ALL"}, "goog:chromeOptions": {"prefs": {"download.default_directory": "/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/downloads", "download.prompt_for_download": false, "download.directory_upgrade": true, "safebrowsing.enabled": false, "profile.default_content_settings.popups": 0, "profile.content_settings.exceptions.automatic_downloads.*.setting": 1}, "excludeSwitches": ["enable-logging", "enable-automation"], "useAutomationExtension": false, "extensions": [], "args": ["--headless=new", "--window-size=1920,1080", "--start-maximized", "--disable-gpu", "--no-sandbox", "--disable-dev-shm-usage", "--disable-extensions", "--disable-popup-blocking", "--ignore-certificate-errors", "--disable-web-security", "--allow-running-insecure-content"]}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:244 Starting new HTTP connection (1): localhost:44135
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:44135 "POST /session HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"140.0.7339.207","chrome":{"chromedriverVersion":"140.0.7339.207 (17230b545fd18b35aad49122e5af97a463bc7a9c-refs/branch-heads/7339@{#2364})","userDataDir":"/tmp/.org.chromium.Chromium.u45mvM"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:34295"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"3f3dc12b9355f41c4a3dd429d5688021"}} | headers=HTTPHeaderDict({'Content-Length': '850', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:44135/session/3f3dc12b9355f41c4a3dd429d5688021/timeouts {"implicit": 10000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:44135 "POST /session/3f3dc12b9355f41c4a3dd429d5688021/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:44135/session/3f3dc12b9355f41c4a3dd429d5688021/timeouts {"pageLoad": 60000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:44135 "POST /session/3f3dc12b9355f41c4a3dd429d5688021/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.address`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.address` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.automotive`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.automotive` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.bank`.
DEBUG    faker.factory:factory.py:86 Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.barcode`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.barcode` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.color`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.color` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.company`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.company` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.credit_card`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.credit_card` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.currency`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.currency` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.date_time`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.date_time` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.geo`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.geo` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.internet`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.internet` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.job`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.job` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.lorem`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.lorem` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.misc`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.misc` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.passport`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.passport` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.person`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.person` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.phone_number`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.phone_number` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.ssn`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.ssn` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:44135/session/3f3dc12b9355f41c4a3dd429d5688021/url {"url": "https://www.demoblaze.com"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:44135 "POST /session/3f3dc12b9355f41c4a3dd429d5688021/url HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1163 Navigated to DemoBlaze website on chrome
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:2255 Testing radio button selection
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:44135/session/3f3dc12b9355f41c4a3dd429d5688021/timeouts {"pageLoad": 30000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:44135 "POST /session/3f3dc12b9355f41c4a3dd429d5688021/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:44135/session/3f3dc12b9355f41c4a3dd429d5688021/url {"url": "https://demo.seleniumeasy.com/basic-radiobutton-demo.html"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:44135 "POST /session/3f3dc12b9355f41c4a3dd429d5688021/url HTTP/1.1" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=500 | data={"value":{"error":"unknown error","message":"unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=140.0.7339.207)","stacktrace":"#0 0x560bac1fffba \u003Cunknown>\n#1 0x560babc846d0 \u003Cunknown>\n#2 0x560babc7b8f8 \u003Cunknown>\n#3 0x560babc6ccb6 \u003Cunknown>\n#4 0x560babc6ea00 \u003Cunknown>\n#5 0x560babc6d05e \u003Cunknown>\n#6 0x560babc6c9dc \u003Cunknown>\n#7 0x560babc6c6b5 \u003Cunknown>\n#8 0x560babc6a53b \u003Cunknown>\n#9 0x560babc6ad1a \u003Cunknown>\n#10 0x560babc87be9 \u003Cunknown>\n#11 0x560babd22715 \u003Cunknown>\n#12 0x560babcfbe32 \u003Cunknown>\n#13 0x560babd21b54 \u003Cunknown>\n#14 0x560babcfbc03 \u003Cunknown>\n#15 0x560babcc87a8 \u003Cunknown>\n#16 0x560babcc9421 \u003Cunknown>\n#17 0x560bac1c4b28 \u003Cunknown>\n#18 0x560bac1c887f \u003Cunknown>\n#19 0x560bac1acc49 \u003Cunknown>\n#20 0x560bac1c9405 \u003Cunknown>\n#21 0x560bac1924ff \u003Cunknown>\n#22 0x560bac1ed258 \u003Cunknown>\n#23 0x560bac1ed432 \u003Cunknown>\n#24 0x560bac1fefa3 \u003Cunknown>\n#25 0x7fa14f09caa4 \u003Cunknown>\n#26 0x7fa14f129c6c \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '1081', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
WARNING  TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:2282 Selenium Easy failed: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=140.0.7339.207)
Stacktrace:
#0 0x560bac1fffba <unknown>
#1 0x560babc846d0 <unknown>
#2 0x560babc7b8f8 <unknown>
#3 0x560babc6ccb6 <unknown>
#4 0x560babc6ea00 <unknown>
#5 0x560babc6d05e <unknown>
#6 0x560babc6c9dc <unknown>
#7 0x560babc6c6b5 <unknown>
#8 0x560babc6a53b <unknown>
#9 0x560babc6ad1a <unknown>
#10 0x560babc87be9 <unknown>
#11 0x560babd22715 <unknown>
#12 0x560babcfbe32 <unknown>
#13 0x560babd21b54 <unknown>
#14 0x560babcfbc03 <unknown>
#15 0x560babcc87a8 <unknown>
#16 0x560babcc9421 <unknown>
#17 0x560bac1c4b28 <unknown>
#18 0x560bac1c887f <unknown>
#19 0x560bac1acc49 <unknown>
#20 0x560bac1c9405 <unknown>
#21 0x560bac1924ff <unknown>
#22 0x560bac1ed258 <unknown>
#23 0x560bac1ed432 <unknown>
#24 0x560bac1fefa3 <unknown>
#25 0x7fa14f09caa4 <unknown>
#26 0x7fa14f129c6c <unknown>

DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:44135/session/3f3dc12b9355f41c4a3dd429d5688021/timeouts {"pageLoad": 59000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:44135 "POST /session/3f3dc12b9355f41c4a3dd429d5688021/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:44135/session/3f3dc12b9355f41c4a3dd429d5688021/url {"url": "https://demoqa.com/radio-button"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:44135 "POST /session/3f3dc12b9355f41c4a3dd429d5688021/url HTTP/1.1" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=500 | data={"value":{"error":"timeout","message":"timeout: Timed out receiving message from renderer: 58.509\n  (Session info: chrome=140.0.7339.207)","stacktrace":"#0 0x560bac1fffba \u003Cunknown>\n#1 0x560babc846d0 \u003Cunknown>\n#2 0x560babc6c9ae \u003Cunknown>\n#3 0x560babc6c6b5 \u003Cunknown>\n#4 0x560babc6a53b \u003Cunknown>\n#5 0x560babc6ae8f \u003Cunknown>\n#6 0x560babc797f3 \u003Cunknown>\n#7 0x560babc92c5b \u003Cunknown>\n#8 0x560babc9944b \u003Cunknown>\n#9 0x560babc6b5cd \u003Cunknown>\n#10 0x560babc92988 \u003Cunknown>\n#11 0x560babd21eba \u003Cunknown>\n#12 0x560babcfbc03 \u003Cunknown>\n#13 0x560babcc87a8 \u003Cunknown>\n#14 0x560babcc9421 \u003Cunknown>\n#15 0x560bac1c4b28 \u003Cunknown>\n#16 0x560bac1c887f \u003Cunknown>\n#17 0x560bac1acc49 \u003Cunknown>\n#18 0x560bac1c9405 \u003Cunknown>\n#19 0x560bac1924ff \u003Cunknown>\n#20 0x560bac1ed258 \u003Cunknown>\n#21 0x560bac1ed432 \u003Cunknown>\n#22 0x560bac1fefa3 \u003Cunknown>\n#23 0x7fa14f09caa4 \u003Cunknown>\n#24 0x7fa14f129c6c \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '1022', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
WARNING  TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:2313 Demoqa failed: Message: timeout: Timed out receiving message from renderer: 58.509
  (Session info: chrome=140.0.7339.207)
Stacktrace:
#0 0x560bac1fffba <unknown>
#1 0x560babc846d0 <unknown>
#2 0x560babc6c9ae <unknown>
#3 0x560babc6c6b5 <unknown>
#4 0x560babc6a53b <unknown>
#5 0x560babc6ae8f <unknown>
#6 0x560babc797f3 <unknown>
#7 0x560babc92c5b <unknown>
#8 0x560babc9944b <unknown>
#9 0x560babc6b5cd <unknown>
#10 0x560babc92988 <unknown>
#11 0x560babd21eba <unknown>
#12 0x560babcfbc03 <unknown>
#13 0x560babcc87a8 <unknown>
#14 0x560babcc9421 <unknown>
#15 0x560bac1c4b28 <unknown>
#16 0x560bac1c887f <unknown>
#17 0x560bac1acc49 <unknown>
#18 0x560bac1c9405 <unknown>
#19 0x560bac1924ff <unknown>
#20 0x560bac1ed258 <unknown>
#21 0x560bac1ed432 <unknown>
#22 0x560bac1fefa3 <unknown>
#23 0x7fa14f09caa4 <unknown>
#24 0x7fa14f129c6c <unknown>
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1168 Test completed on chrome
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1169 ==================================================
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 DELETE http://localhost:44135/session/3f3dc12b9355f41c4a3dd429d5688021 {}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:44135 "DELETE /session/3f3dc12b9355f41c4a3dd429d5688021 HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request