INFO     TestDemoBlazeE2E_edge:test_demoblaze_e2e.py:1142 ==================================================
INFO     TestDemoBlazeE2E_edge:test_demoblaze_e2e.py:1143 Starting new test on EDGE
DEBUG    selenium.webdriver.common.service:service.py:215 Started executable: `/usr/local/bin/msedgedriver` in a child process with pid: 3624
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:36997/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "MicrosoftEdge", "pageLoadStrategy": "normal", "ms:edgeOptions": {"prefs": {"download.default_directory": "/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/downloads", "download.prompt_for_download": false, "download.directory_upgrade": true, "safebrowsing.enabled": false, "profile.default_content_settings.popups": 0, "profile.default_content_setting_values.notifications": 2}, "excludeSwitches": ["enable-logging", "enable-automation"], "useAutomationExtension": false, "extensions": [], "args": ["--headless=new", "--window-size=1920,1080", "--start-maximized", "--disable-gpu", "--no-sandbox", "--disable-dev-shm-usage", "--disable-software-rasterizer", "--disable-blink-features=AutomationControlled", "--single-process", "--disable-features=VizDisplayCompositor", "--disable-setuid-sandbox", "--disable-extensions", "--disable-popup-blocking", "--ignore-certificate-errors"]}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:244 Starting new HTTP connection (1): localhost:36997
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:36997 "POST /session HTTP/1.1" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=500 | data={"value":{"error":"session not created","message":"session not created: No matching capabilities found","stacktrace":"#0 0x56173828efba \u003Cunknown>\n#1 0x561737d136d0 \u003Cunknown>\n#2 0x561737d97e12 \u003Cunknown>\n#3 0x561737d96f9e \u003Cunknown>\n#4 0x561737d98b72 \u003Cunknown>\n#5 0x561737d98946 \u003Cunknown>\n#6 0x561737d8ac03 \u003Cunknown>\n#7 0x561737d577a8 \u003Cunknown>\n#8 0x561737d58421 \u003Cunknown>\n#9 0x561738253b28 \u003Cunknown>\n#10 0x56173825787f \u003Cunknown>\n#11 0x56173823bc49 \u003Cunknown>\n#12 0x561738258405 \u003Cunknown>\n#13 0x5617382214ff \u003Cunknown>\n#14 0x56173827c258 \u003Cunknown>\n#15 0x56173827c432 \u003Cunknown>\n#16 0x56173828dfa3 \u003Cunknown>\n#17 0x7fe2b849caa4 \u003Cunknown>\n#18 0x7fe2b8529c6c \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '776', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:63 Selenium Manager binary found at: /opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:120 Executing process: /opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/linux/selenium-manager --browser MicrosoftEdge --debug --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Found msedgedriver 140.0.7339.207 in PATH: /usr/local/bin/msedgedriver
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 MicrosoftEdge detected at /usr/bin/microsoft-edge
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Running command: /usr/bin/microsoft-edge --version
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Output: "Microsoft Edge 141.0.3537.99 "
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Detected browser: MicrosoftEdge 141.0.3537.99
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Reading msedgedriver version from https://msedgedriver.azureedge.net/LATEST_RELEASE_141_LINUX
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:135 Exception managing MicrosoftEdge: error sending request for url (https://msedgedriver.azureedge.net/LATEST_RELEASE_141_LINUX): error trying to connect: dns error: failed to lookup address information: Name does not resolve
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:135 The msedgedriver version (140.0.7339.207) detected in PATH at /usr/local/bin/msedgedriver might not be compatible with the detected MicrosoftEdge version (141.0.3537.99); currently, msedgedriver  is recommended for MicrosoftEdge 141.*, so it is advised to delete the driver in PATH and retry
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Driver path: /usr/local/bin/msedgedriver
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Browser path: /usr/bin/microsoft-edge
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:98 Using driver at: /usr/local/bin/msedgedriver
DEBUG    selenium.webdriver.common.service:service.py:215 Started executable: `/usr/local/bin/msedgedriver` in a child process with pid: 3724
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:47627/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "MicrosoftEdge", "pageLoadStrategy": "normal", "browserVersion": null, "ms:edgeOptions": {"prefs": {"download.default_directory": "/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/downloads", "download.prompt_for_download": false, "download.directory_upgrade": true, "safebrowsing.enabled": false, "profile.default_content_settings.popups": 0, "profile.default_content_setting_values.notifications": 2}, "excludeSwitches": ["enable-logging", "enable-automation"], "useAutomationExtension": false, "extensions": [], "binary": "/usr/bin/microsoft-edge", "args": ["--headless=new", "--window-size=1920,1080", "--start-maximized", "--disable-gpu", "--no-sandbox", "--disable-dev-shm-usage", "--disable-software-rasterizer", "--disable-blink-features=AutomationControlled", "--single-process", "--disable-features=VizDisplayCompositor", "--disable-setuid-sandbox", "--disable-extensions", "--disable-popup-blocking", "--ignore-certificate-errors"]}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:244 Starting new HTTP connection (1): localhost:47627
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:47627 "POST /session HTTP/1.1" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=500 | data={"value":{"error":"session not created","message":"session not created: No matching capabilities found","stacktrace":"#0 0x555ec682bfba \u003Cunknown>\n#1 0x555ec62b06d0 \u003Cunknown>\n#2 0x555ec6334e12 \u003Cunknown>\n#3 0x555ec6333f9e \u003Cunknown>\n#4 0x555ec6335b72 \u003Cunknown>\n#5 0x555ec6335946 \u003Cunknown>\n#6 0x555ec6327c03 \u003Cunknown>\n#7 0x555ec62f47a8 \u003Cunknown>\n#8 0x555ec62f5421 \u003Cunknown>\n#9 0x555ec67f0b28 \u003Cunknown>\n#10 0x555ec67f487f \u003Cunknown>\n#11 0x555ec67d8c49 \u003Cunknown>\n#12 0x555ec67f5405 \u003Cunknown>\n#13 0x555ec67be4ff \u003Cunknown>\n#14 0x555ec6819258 \u003Cunknown>\n#15 0x555ec6819432 \u003Cunknown>\n#16 0x555ec682afa3 \u003Cunknown>\n#17 0x7f3c4ea9caa4 \u003Cunknown>\n#18 0x7f3c4eb29c6c \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '776', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request